### ISSUE TITLE
Programmatically enter and exit full screen?

### ISSUE THREAD

**Issue by emadd** [mwaqasbhati/MBVideoPlayer#1]
We have a special use case that requires the end user to enter and exit full screen mode programmatically, but it doesn't seem possible with your library.  The only full screen option appear to be enabling a button for toggling full screen.  Can you update your library to provide a method for toggling full screen?

**Comment by mwaqasbhati** [comment]
Now I have given a function which you can call to toggle your screen `toggleScreen()` and it will do the purpose.
