### ISSUE TITLE
Slider not working

### ISSUE THREAD

**Issue by santhoshappdev** [mwaqasbhati/MBVideoPlayer#6]
Video is playing fine. but  slider not moving forward
![Screenshot 2021-08-31 at 11 45 46 AM](https://user-images.githubusercontent.com/35039366/131451690-9b681933-0872-4865-9932-0d5197428ff0.png)

**Comment by mwaqasbhati** [comment]
@santhoshappdev  did you try using example project ? if not then can you please check by using example project.

**Comment by santhoshappdev** [comment]
Yes, Example project only i checked

**Comment by mwaqasbhati** [comment]
Issue is fixed
